# Generated by Django 5.1.4 on 2024-12-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pcapfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PcapFile',
        ),
    ]
