# Generated by Django 5.1.4 on 2024-12-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_delete_pcapfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalies_detected', models.IntegerField()),
                ('average_latency', models.FloatField()),
                ('optimizations', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='projects.project')),
            ],
        ),
    ]
