# Generated by Django 5.1.4 on 2024-12-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='optimizations',
            field=models.JSONField(default=list),
        ),
    ]
