# Generated by Django 5.1.4 on 2024-12-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisresult_average_jitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='anomaly_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='protocol',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
